### ISSUE TITLE
How to add and use this library in Gridsome

### ISSUE THREAD

**Issue by HUSEN88** [alexandermendes/vue-confetti#40]
`Could not generate HTML for "/workshops/Journalism-&-Media-Studies/":
ReferenceError: window is not defined
    at Object.<anonymous> (node_modules/vue-confetti/dist/vue-confetti.js:1:210)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (assets/js/app.1b103b72.js:43910:20)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.module.exports.module.exports (assets/js/app.1b103b72.js:5973:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at assets/js/app.1b103b72.js:118:18
    at Object.<anonymous> (assets/js/app.1b103b72.js:121:10)
    at o (D:\angular\climber-website\node_modules\vue-server-renderer\build.prod.js:1:77543)
    at D:\angular\climber-website\node_modules\vue-server-renderer\build.prod.js:1:78136
`
I am using vue-confetti package in my application but it's giving the below error while building, I wanted to know how to overcome this error with how to make it to only render at the client-side using Gridsome.

**Comment by alexandermendes** [comment]
I'm not familiar with Gridsome, but from a quick search it looks like you can surround components with `<ClientOnly></ClientOnly>`?

https://gridsome.org/docs/assets-scripts/#without-ssr-support

In any case, this is really a question of how to render client-side only components in Gridsome, not really one for this library.
